#!/bin/env bash
backup_dir="/home/user_space/Backups"
wp_db_pass="pass_phrase"
wp_database="wp-DB"
wp_root_dir="/var/www/html"
db_backup_name=""$wp_database"_`date +%Y-%M-%d-%H:%M:%S`".sql
wp_backup_files=""$backup_dir/wp_files"_`date +%Y-%M-%d-%H:%M:%S`"
curdate=$(date +"%Y-%M-%d-%H:%M:%S")

#------------=======Functions========------------
cd "$backup_dir"

clean_old_files () {
 echo -e "Deleting old files....."
 find "$backup_dir" -type f -mtime +7 -exec rm -f {} \;

}

backup_db () {
 echo -e "Creating mysql DB backup"
 cd "$backup_dir"
 mysqldump -u root -p$wp_db_pass "$wp_database" > "$db_backup_name"
}

backup_wp_files () {
 echo -e "Creating WP files backup"
 tar -cvf "$wp_backup_files".tar /var/www/html

}

clean_old_files
backup_db
backup_wp_files
