#!/bin/env bash
backup_dir="/home/user_space/Backups"
wp_db_pass="pass_phrase"
wp_database="WP_DB"
wp_root_dir="/var/www/html"
db_backup_name=""$wp_database"_`date +%Y-%m-%d_%H_%M_%S`".sql
wp_backup_files=""$backup_dir/wp_files"_`date +%Y-%m-%d_%H_%M_%S`"
curdate=$(date +"%Y-%M-%d-%H:%M:%S")

#------------=======Functions========------------

clean_old_files () {
   echo -e "Deleting old files....."
   find "$backup_dir" -type f -mtime +7 -exec rm -f {} \;

}

backup_db () {
   echo -e "Creating mysql DB backup"
   cd "$backup_dir"
   mysqldump -u root -p$wp_db_pass "$wp_database" > "$db_backup_name"
}

backup_wp_files () {
   echo -e "Creating WP files backup"
   tar -czvf "$wp_backup_files".tar.gz /var/www/html

}

cd "$backup_dir"
clean_old_files
backup_db
backup_wp_files
